[build]
  functions = "netlify/functions"  # Esto indica que las funciones están en la carpeta netlify/functions
  publish = "public"  # Carpeta donde se encuentra el contenido estático, si tienes archivos frontend

[dev]
  functions = "netlify/functions"
  publish = "public"
